as/c:
  fuzzy_mpc:
    ros__parameters:
      MPC:
        latency: 2.0
        q_lat: 1.0 
        q_vy: 0.0
        q_phi: 0.0 
        q_r: 0.0
        q_delta: 0.0
        r_delta: 0.3

        p_lat: 1.0
        p_vy: 0.0
        p_phi: 0.0
        p_r: 0.0
        p_delta: 0.0
