as/c:  
  fuzzy_mpc:
    ros__parameters:

      verbose: false
      save_debug: true
      profile: true
      debug_path: "/src/as/control/fuzzy_mpc/debug"  # Debug path from ROS2 workspace
      
      MPC:
        Ts: 0.02           # [s] Sampling time 
        n_horizon: 60     # Number of steps in the horizon
        latency: 0.0      # [s] Latency to compensate for in the MPC

        # Scalings to normalize weights and state evaluation
        scale_y: 0.1      # [m]
        scale_vy: 0.1     # [m/s]
        scale_phi: 0.05   # [rad]
        scale_r: 0.05     # [rad/s]
        scale_st: 0.2     # [rad]
        scale_dst: 0.001  # [rad/Ts]
        scale_mz: 1000.0  # [Nm]
        scale_dmz: 1000.0 # [Nm/Ts]

      Car:
        m: 220.0      # Car's mass
        I: 188.0      # Inertial moment (180) (128)
        Lf: 0.765     # Distance from CoG to front axis (0.708) 
        Lr: 0.765     # Distance from CoG to rear axis (0.822) 
        Bf: 10.5507   # 10.8529
        Br: 10.5507   # 10.1507
        Cf: 1.2705    #-1.1705 
        Cr: 1.2705    #-1.1705 
        Df: 1104.0    # 2208.0635*0.5
        Dr: 1281.5    # 2563.599*0.5

        steering_damp: 0.5      # Damping factor for the slip angle dynamics
        steering_omega: 16.0    # Natural frequency for the slip angle dynamics


      Topics:
        InState: /as/c/state
        InPlanner: /as/c/locator
        InVelocities: /as/c/log_pid/velocity
        OutSteering: /as/c/steering
        OutDuration: /as/c/mpc/debug/time
        Vis:
          PredictedSteering:  /vis/predictedPath/steering
          PredictedPath:      /vis/predictedPath/path
          PredictedHeading:   /vis/predictedPath/heading
          ReferencePath:      /vis/referencePath
        Debug:
          OutLateralError: /as/c/mpc/debug/lateralError
          OutHeadingError: /as/c/mpc/debug/headingError
          OutYawRateRef: /as/c/yawRateRef
        
