as/c:  
  fuzzy_mpc:
    ros__parameters:

      verbose: false
      save_debug: false
      profile: true
      debug_path: "/src/as/control/fuzzy_mpc/debug/csv"  # Where in your ws to save csv
      
      MPC:
        Ts: 0.02          # [s] Sampling time (must be trained Ts for ANFIS model)
        n_horizon: 60     # Number of steps in the horizon
        n_evaluation: 60  # Number of steps to evaluate model error on
        model: "ltv"      # ltv or anfis_direct

        # Limits
        max_steering: 0.38        # [rad] Maximum steering command
        max_delta: 0.45           # [rad] Maximum measured steering position
        max_steering_dot: 1.396   # [rad/s] Maximum steering rate

        # Scalings to normalize weights and state evaluation
        scale_y: 0.1      # [m]
        scale_vy: 0.1     # [m/s]
        scale_psi: 0.05   # [rad]
        scale_r: 0.05     # [rad/s]
        scale_st: 0.2     # [rad]
        scale_dst: 0.001  # [rad/Ts]

      Car:
        m: 207.0      # Car mass used by the MATLAB LTV model
        I: 129.024    # Yaw inertia used by the MATLAB LTV model
        Lf: 0.765     # Distance from CoG to front axis (0.708) 
        Lr: 0.765     # Distance from CoG to rear axis (0.822) 
        Bf: 10.5507   # 10.8529
        Br: 10.5507   # 10.1507
        Cf: -1.2705    #-1.1705 
        Cr: -1.2705    #-1.1705 
        Df: 1104.0    # 2208.0635*0.5
        Dr: 1281.5    # 2563.599*0.5

        steering_damp: 0.5      # Damping factor for the steering dynamics
        steering_omega: 16.0    # Natural frequency for the steering dynamics


      Topics:
        InState: /as/c/state
        InPlanner: /as/c/locator
        InVelocities: /as/c/log_pid/velocity
        OutSteering: /as/c/steering
        OutModelError: /as/c/mpc/model_error
        Vis:
          PredictedSteering:  /vis/predictedPath/steering
          PredictedPath:      /vis/predictedPath/path
          PredictedHeading:   /vis/predictedPath/heading
          ReferencePath:      /vis/referencePath
        Debug:
          OutLateralError: /as/c/mpc/debug/lateralError
          OutHeadingError: /as/c/mpc/debug/headingError
          OutYawRateRef: /as/c/yawRateRef
        
